import { inter } from "@/config/fonts";
import classes from "./Layout.module.css";

export const metadata = {
  title: "Auth",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={classes.wrapper}>
      <div className={`${classes["content-container"]} ${inter.className}`}>
        {children}
      </div>
    </main>
  );
}
